### ISSUE TITLE
Error Importing Capstone

### ISSUE THREAD

**Issue by gregkcarson** [Intezer/MemoryPatchDetector#3]
Hey There,

I've run a pip install capstone and it succeeded but when I go to run to run the tool I get a Import Error: No Module Named Capstone.

Python 2.7 on Windows 7.

Any ideas? Could be a trick to installing capstone on Windows? Any methodology you have there? I used the following for library imports: https://sites.google.com/site/pydatalog/python/pip-for-windows

Any chance you could compile everything to an executable to eliminate dependencies?

**Comment by ItaiTevet** [comment]
Hi Greg,
You can install Capstone on Windows using their precompiled binaries:
http://www.capstone-engine.org/download.html

Let me know if you encounter any other problem
